### ISSUE TITLE
Pre-loader never ends on mobile... and minor errors

### ISSUE THREAD

**Issue by infinotiver** [Senarc-Studios/Website#1]
![image](https://github.com/Senarc-Studios/Website/assets/88645086/43257e2f-83b4-4cd5-80e8-f0b1b8c53f53)
1. **Works perfectly on desktop but on mobile the pre loader never ends**
The pre loader on mobile phones or smaller devices never ends, I tried 3 different devices
___

![image](https://github.com/Senarc-Studios/Website/assets/88645086/84eced28-36ca-47b0-94b3-2b3762ab5e31)

2. **O  seems more like U**
3. The website changes too much on a little smaller laptops also ...

**Comment by infinotiver** [comment]
Wrong repository, forgot @BenitzCoding is on break and the new website is on @rohansharma-developer's profile...

**Comment by infinotiver** [comment]
Wrong repository, forgot @BenitzCoding is on break and the new website is on @rohansharma-developer's profile...

**Comment by rohansharma-developer** [comment]
It look like some asset takes too much time to load….it is not actually a bug. It is an issue with some asset

**Comment by rohansharma-developer** [comment]
For the time being, should I remove the preloader?
